#!/bin/bash
#
# Deploy breath_sensor to Raspberry Pi running QNX
# Sets up the binary and configures auto-start on boot
#
# Usage: ./install.sh <PI_IP> <RAILWAY_API_URL>
#
# Example:
#   ./install.sh 192.168.1.100 https://my-api.railway.app
#

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
BINARY_NAME="breath_sensor"
BINARY_PATH="${PROJECT_DIR}/${BINARY_NAME}"

# Remote paths on QNX
REMOTE_BIN_DIR="/usr/local/bin"
REMOTE_LOG_DIR="/var/log"
REMOTE_RC_DIR="/etc/rc.d"
REMOTE_CONF_FILE="/etc/breath_sensor.conf"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Parse arguments
if [ $# -lt 2 ]; then
    echo "Usage: $0 <PI_IP> <RAILWAY_API_URL>"
    echo ""
    echo "Arguments:"
    echo "  PI_IP           - IP address of the Raspberry Pi"
    echo "  RAILWAY_API_URL - Full URL of the Railway API endpoint"
    echo ""
    echo "Example:"
    echo "  $0 192.168.1.100 https://my-api.railway.app"
    exit 1
fi

PI_IP="$1"
API_URL="$2"

# Validate inputs
if [[ ! "${PI_IP}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    log_error "Invalid IP address: ${PI_IP}"
    exit 1
fi

if [[ ! "${API_URL}" =~ ^https?:// ]]; then
    log_error "Invalid API URL (must start with http:// or https://): ${API_URL}"
    exit 1
fi

# Check binary exists
if [ ! -f "${BINARY_PATH}" ]; then
    log_error "Binary not found: ${BINARY_PATH}"
    log_info "Run './build.sh' first to compile the application."
    exit 1
fi

log_info "Deploying ${BINARY_NAME} to ${PI_IP}"
log_info "API URL: ${API_URL}"

# Test SSH connection
log_info "Testing SSH connection..."
if ! ssh -o ConnectTimeout=5 -o BatchMode=yes "qnxuser@${PI_IP}" "echo 'SSH OK'" 2>/dev/null; then
    log_error "Cannot connect to qnxuser@${PI_IP}"
    log_info "Make sure:"
    log_info "  1. The Pi is running and connected to the network"
    log_info "  2. SSH is enabled on the Pi"
    log_info "  3. You have SSH key access to qnxuser@${PI_IP}"
    exit 1
fi

# Create remote directories
log_info "Creating remote directories..."
ssh "qnxuser@${PI_IP}" "mkdir -p ${REMOTE_BIN_DIR} ${REMOTE_LOG_DIR} ${REMOTE_RC_DIR}"

# Copy binary
log_info "Copying binary to ${REMOTE_BIN_DIR}/${BINARY_NAME}..."
scp "${BINARY_PATH}" "qnxuser@${PI_IP}:${REMOTE_BIN_DIR}/${BINARY_NAME}"
ssh "qnxuser@${PI_IP}" "chmod +x ${REMOTE_BIN_DIR}/${BINARY_NAME}"

# Create configuration file
log_info "Creating configuration file..."
ssh "qnxuser@${PI_IP}" "cat > ${REMOTE_CONF_FILE}" << EOF
# Breath Sensor Configuration
# Generated by install.sh on $(date)

# Railway API endpoint URL
RAILWAY_API_URL=${API_URL}

# SPI device path (default: /dev/spi0)
#SPI_DEVICE=/dev/spi0

# Polling interval in milliseconds (default: 500)
#POLL_INTERVAL_MS=500
EOF

# Create startup script
log_info "Installing startup script..."
ssh "qnxuser@${PI_IP}" "cat > ${REMOTE_RC_DIR}/rc.breath_sensor" << 'RCEOF'
#!/bin/sh
#
# Breath Sensor startup script
# Starts breath_sensor on boot
#

BINARY="/usr/local/bin/breath_sensor"
CONF_FILE="/etc/breath_sensor.conf"
LOG_FILE="/var/log/breath_sensor.log"
PID_FILE="/var/run/breath_sensor.pid"

# Load configuration
if [ -f "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    export RAILWAY_API_URL
    export SPI_DEVICE
    export POLL_INTERVAL_MS
fi

start() {
    if [ -f "${PID_FILE}" ] && kill -0 $(cat "${PID_FILE}") 2>/dev/null; then
        echo "breath_sensor is already running"
        return 1
    fi

    echo "Starting breath_sensor..."
    
    # Wait for network
    sleep 5
    
    # Start the application
    "${BINARY}" >> "${LOG_FILE}" 2>&1 &
    echo $! > "${PID_FILE}"
    
    echo "breath_sensor started (PID: $(cat ${PID_FILE}))"
}

stop() {
    if [ ! -f "${PID_FILE}" ]; then
        echo "breath_sensor is not running (no PID file)"
        return 1
    fi
    
    PID=$(cat "${PID_FILE}")
    if kill -0 "${PID}" 2>/dev/null; then
        echo "Stopping breath_sensor (PID: ${PID})..."
        kill "${PID}"
        rm -f "${PID_FILE}"
        echo "breath_sensor stopped"
    else
        echo "breath_sensor is not running"
        rm -f "${PID_FILE}"
    fi
}

status() {
    if [ -f "${PID_FILE}" ] && kill -0 $(cat "${PID_FILE}") 2>/dev/null; then
        echo "breath_sensor is running (PID: $(cat ${PID_FILE}))"
    else
        echo "breath_sensor is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
RCEOF

ssh "qnxuser@${PI_IP}" "chmod +x ${REMOTE_RC_DIR}/rc.breath_sensor"

# Add to rc.local for auto-start
log_info "Configuring auto-start..."
ssh "qnxuser@${PI_IP}" << 'AUTOSTART'
# Ensure rc.local exists and has our startup command
RC_LOCAL="/etc/rc.d/rc.local"

# Create rc.local if it doesn't exist
if [ ! -f "${RC_LOCAL}" ]; then
    echo '#!/bin/sh' > "${RC_LOCAL}"
    echo '# Local startup script' >> "${RC_LOCAL}"
    chmod +x "${RC_LOCAL}"
fi

# Add breath_sensor startup if not already present
if ! grep -q "rc.breath_sensor" "${RC_LOCAL}"; then
    echo '' >> "${RC_LOCAL}"
    echo '# Start breath sensor' >> "${RC_LOCAL}"
    echo '/etc/rc.d/rc.breath_sensor start' >> "${RC_LOCAL}"
    echo "Added breath_sensor to ${RC_LOCAL}"
else
    echo "breath_sensor already in ${RC_LOCAL}"
fi
AUTOSTART

# Verify installation
log_info "Verifying installation..."
ssh "qnxuser@${PI_IP}" "ls -la ${REMOTE_BIN_DIR}/${BINARY_NAME}"
ssh "qnxuser@${PI_IP}" "cat ${REMOTE_CONF_FILE}"

echo ""
log_info "========================================="
log_info "Deployment complete!"
log_info "========================================="
echo ""
log_info "The application will start automatically on boot."
echo ""
log_info "Manual control commands (run on Pi):"
echo "  Start:   /etc/rc.d/rc.breath_sensor start"
echo "  Stop:    /etc/rc.d/rc.breath_sensor stop"
echo "  Status:  /etc/rc.d/rc.breath_sensor status"
echo "  Restart: /etc/rc.d/rc.breath_sensor restart"
echo ""
log_info "View logs:"
echo "  tail -f /var/log/breath_sensor.log"
echo ""
log_info "Edit configuration:"
echo "  vi /etc/breath_sensor.conf"
echo ""

# Ask if user wants to start now
read -p "Start breath_sensor now? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Starting breath_sensor..."
    ssh "qnxuser@${PI_IP}" "/etc/rc.d/rc.breath_sensor start"
fi
